! parizek_17lqmt.scl
!April 2004 - Petr Parizek
!To tune the scale by ear, please choose the intervals in the following order:
!Eb-F#, Eb-G, G-B, Eb-G#, G#-Bb, Bb-D, Bb-F, G#-C#, G#-E, E-A, A-C.
!It's good to begin the tuning in some higher octaves to be able to hear
!the characteristic timbre of the Eb-G# interval (i.e. 17/13 in this scale).
!
17-limit Quasi-meantone
 12
!
 25/24
 125/112
 325/272
 5/4
 75/56
 2275/1632
 1625/1088
 25/16
 5/3
 25/14
 8125/4352
 2/1
