#-------------------------------------------------------------------------------
# Name:         ismir2010.py
# Purpose:      Examples for ISMIR 2010 paper
#
# Authors:      Christopher Ariza
#               Michael Scott Cuthbert
#
# Copyright:    (c) 2009-2010 The music21 Project
# License:      LGPL
#-------------------------------------------------------------------------------


from music21 import *

def example2():
    handel = corpus.parse('hwv56/movement3-05.md')
    fe = features.jSymbolic.TripleMeterFeature(handel)
    print fe.extract().vector

    soft = converter.parse("http://static.wikifonia.org/10699/musicxml.xml")
    fe.setData(soft)
    print fe.extract().vector

class MusicaFictaFeature(features.FeatureExtractor):
    name = 'Musica Ficta'
    discrete = False
    dimensions = 1
    
    def _process(self):
        allPitches = self._src.flat.pitches
        fictaPitches = 0
        for p in allPitches:
            if p.name == "B-":
                continue
            elif p.accidental is not None and p.accidental.name != 'natural':
                fictaPitches += 1
        self._feature.vector[0] = \
           fictaPitches / float(len(allPitches))
            
def testFictaFeature():
    luca = corpus.parse('luca/gloria.mxl')
    fe = MusicaFictaFeature(luca)
    print fe.extract().vector
    mv = corpus.parse('monteverdi/madrigal.3.1.xml')
    fe.setData(mv)
    print fe.extract().vector

def testDataSet():
    fes = features.extractorsById(['ql1','ql2','ql3'])
    ds = features.DataSet(classLabel='Composer')
    ds.addFeatureExtractors(fes)
    
    b1 = corpus.parse('bwv1080', 7).measures(0,50)
    ds.addData(b1, classValue='Bach', id='artOfFugue')
    ds.addData('bwv66.6.xml', classValue='Bach')
#    ds.addData('c:/handel/hwv56/movement3-05.md', 
    ds.addData('hwv56/movement3-05.md', 
                    classValue='Handel')
    ds.addData('http://www.midiworld.com/midis/other/handel/gfh-jm01.mid')
    ds.process()
    print ds.getAttributeLabels()
    ds.write('d:/desktop/baroqueQLs.csv')
    fList = ds.getFeaturesAsList()
    print fList[0]
    print features.OutputTabOrange(ds).getString()
    for i in range(len(fList)):
        # display scores as pngs generated by Lilypond 
        # if the most common note is an eighth note (0.5)
        # (finds the two Handel scores)
        if fList[i][2] == 0.5:
            pass
#            ds.streams[i].show('lily.png')

    p = graph.PlotFeatures(ds.streams, fes[1:], roundDigits = 2)
    p.process()

def prepareChinaEurope():
    featureExtractors = features.extractorsById(['r31', 'r32', 'r33', 'r34', 'r35', 'p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9', 'p10', 'p11', 'p12', 'p13', 'p14', 'p15', 'p16', 'p19', 'p20', 'p21'])

    oChina1 = corpus.parse('essenFolksong/han1')
    oCEurope1 = corpus.parse('essenFolksong/boehme10')

    ds = features.DataSet(classLabel='Region')
    ds.addFeatureExtractors(featureExtractors)
        
    # add works, defining the class value 
    for w in oChina1.scores:
        id = 'essenFolksong/%s-%s' % ('han1', w.metadata.number)
        ds.addData(w, classValue='China', id=id)

    for w in oCEurope1.scores:
        id = 'essenFolksong/%s-%s' % ('europe1', w.metadata.number)
        ds.addData(w, classValue='CentralEurope', id=id)
    # process with all feature extractors, store all features
    ds.process()
    ds.write('d:/desktop/1a.tab')

def testChinaEurope():
    import orange, orngTree
    data1 = orange.ExampleTable('d:/desktop/1.tab')
    data2 = orange.ExampleTable('d:/desktop/2.tab')

    learners = {}
    learners['maj'] = orange.MajorityLearner
    learners['bayes'] = orange.BayesLearner
    learners['tree'] = orngTree.TreeLearner
    learners['knn'] = orange.kNNLearner

    for cName in learners.keys():
        cType = learners[cName]
        for cData, cStr, matchData, matchStr in [
                                                 (data1, 'file1', data2, 'file2'),
                                                 (data2, 'file2', data1, 'file1'),
                                                 ]:
            # train with data1
            classifier = cType(cData)
            mismatch = 0
            for i in range(len(matchData)):
                c = classifier(matchData[i])
                if c != matchData[i].getclass():
                    mismatch += 1
            print('%s %s: misclassified %s/%s of %s' % (cStr, cName, mismatch, len(matchData),  matchStr))

prepareChinaEurope()
#testDataSet()
#testFictaFeature()
#example2()


#------------------------------------------------------------------------------
# eof
