# -*- coding: utf-8 -*-
#-------------------------------------------------------------------------------
# Name:         exceptions21.py
# Purpose:      music21 Exceptions (called out to not require import music21 to access)
#
# Authors:      Michael Scott Cuthbert
#
# Copyright:    Copyright © 2012 Michael Scott Cuthbert and the music21 Project
# License:      LGPL or BSD, see license.txt
#-------------------------------------------------------------------------------
'''
module to hold exceptions generated by music21, particularly the ``Music21Exception``
which all other m21 exceptions should derive from.

Do not import anything within this module.  Needs to be import free so other modules
can freely import from it.
'''


class Music21Exception(Exception):
    pass

class StreamException(Music21Exception):
    pass


# should be renamed:
class GroupException(Music21Exception):
    pass

class MetadataException(Music21Exception):
    pass

class AnalysisException(Music21Exception):
    pass

class TimespanException(Music21Exception):
    pass


