! Boomsliter.scl
!
Boomsliter & Creel basic set of their referential tuning.                       
 12
!
 9/8
 7/6
 6/5
 5/4
 4/3
 7/5
 3/2
 8/5
 5/3
 7/4
 9/5
 2/1
!For major melodies, transpose it 4 times by 3/2. For minor, transposeit first 
!by 6/5 then this transposed set 3 more times by 3/2. For Blues, the initial
!transposition is by 5/4, then a chain of 3 3/2's. 3 more levels by 3/2's are
!optional 
